### ISSUE TITLE
Comment on each file in uploading via zip

### ISSUE THREAD

**Issue by yukimoritani** [himorin/docsrv#25]
When uploading documents via zip, it is better to put comment on each file.
- prepare a file listing comments (xml or JSON?)

**Comment by himorin** [comment]
tsv format

* 1st line as header, contains order of values by key
* starting from 2nd line, configurations are listed one file per line

json format

* organized as an array of hashes, hash keys are pre-defined (same as tsv one)

operation

* add additional file input at upload window for tsv or json, add one option checkbox to check configuration file or not
* at 1st upload, load and parse uploaded config file (in tsv or json), and import into internal structure
* if check configuration file is enabled, save into webdav space as zip-filename.json in json encoded (zip is temporary saved into  webdav space), and return list of valid configurations (ones taken into internal structure) with zip-filename in webdav space for next processing
