### ISSUE TITLE
Merge existing documents

### ISSUE THREAD

**Issue by yukimoritani** [himorin/docsrv#35]
At present, one cannot merge existing documents, although add a new.
It is helpful if one can merge the documents after uploading.

**Comment by himorin** [comment]
specification on merge/division of document

- add a link in detail information page of document (docinfo) to new edit page (docmerge; admin only)
- docmerge takes one parameter (did)
- after operation, docmerge redirects to docinfo with merge target document

in docmerge page

- display list of files in specified document, with select button for each file, also have 'select all'
- target selection panel with path and target document selector below the list, with creating new document possible
- show checkbox (default on) to specify whether delete old document if 'select all' (makes old document empty)
- options for file versions in target document: keep existing, renumber all based on datetime

**Comment by yukimoritani** [comment]
Thank you for working for this.
I have a couple of questions:
- What do you mean by "one parameter" ?
- Regarding the last bullet, there seems possibility of conflict in five versions. How do you plan are they dealt with?
- Could you explain specifically how document ID of merged files will be? (New? or One of the files?) Also, old ID will be invalid?  I'm imaging a case that one has a URL with old ID, without knowing document has been merged.

**Comment by himorin** [comment]
- docmerge.cgi will take one parameter (did)
- multiple files in the same document can have the same version number (specification of 'version')
- document id is the identification of a document, so once file(s) moved from one document to another, these file(s) will have only a document id of the new document.

**Comment by himorin** [comment]
For security flag and group permission, target document will have:

- security flag of (SOURCE or TARGET), so TARGET will have security flag set if TARGET is not set and SOURCE is set
- group permission (access_doc) as (SOURCE and TARGET), so TARGET in access_doc will have _AndGroupList(ListFullDocRestrict(SOURCE), ListDocRestrict(TARGET))

**Comment by yukimoritani** [comment]
Well, I understand multiple files stored as "different document" may have the same version number, as you pointed out.
My question is what happens if you merge document A with version 1 to document B with version 2?
Do the document server alert us?
