### ISSUE TITLE
Fix call to make zip file function

### ISSUE THREAD

**Issue by yukimoritani** [himorin/docsrv#58]
The blow document is inaccessible:
 https://pfs.ipmu.jp/docsrv/docinfo.cgi?did=1202

**Comment by yukimoritani** [comment]
Atsushi commented that he forgot moving this to "MakeEncrypted". (po 22103)

**Comment by himorin** [comment]
This is a regression by #66578fa, missing replacement from PSMT::File->MakeEncZipFile to PSMT::Archive->MakeEncrypted.
