### ISSUE TITLE
Error occurs in downloading a folder

### ISSUE THREAD

**Issue by yukimoritani** [himorin/docsrv#90]
When we download a folder via "download file" button, an error occurred.
The error message is

> Software error:
Type of argument to keys on reference must be unblessed hashref or arrayref at /server/httpd/docsrv/soft/dirget.cgi line 67.
For help, please send mail to the webmaster (pfs@pfs.ipmu.jp), giving this error message and the time and date of the error.

Atsushi suspect issue in Perl version, but strangely, OS of the server has not been updated..

**Comment by himorin** [comment]
it seems current deployed version was one beyond HEAD, and after updating to 9b30c3f it seems working.
could you check @yukimoritani @naoyukitamura?

**Comment by himorin** [comment]
ah, no. it could occur when you tried to get a point which has empty path in its childs.. could you point which pathid was failed? (please give me by id, not name, for security reason...)

**Comment by yukimoritani** [comment]
"3 MCS", for example.
